
# This is an example config file for the Edge Functions feature
# This file is expected to be at the root of the supabase/functions directory

# Project ID
project_id = "aojrdgobdavxjpnymskc"

[chat]
verify_jwt = false

[restock-check]
verify_jwt = false

[suggest-tasks]
verify_jwt = false

[upload-product-images]
verify_jwt = false

[upload-marketplace-icons]
verify_jwt = false

[execute-flow-block]
verify_jwt = false

[jarvio-assistant]
verify_jwt = false

[generate-task-steps]
verify_jwt = false

[update-task-state]
verify_jwt = false

[enhanced-task-suggestions]
verify_jwt = false

[generate-flow]
verify_jwt = false
