
project_id = "aojrdgobdavxjpnymskc"

[api]
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
site_url = "https://lovable-task-manager.vercel.app"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[functions.generate-task-steps]
verify_jwt = false

[functions.suggest-tasks]
verify_jwt = false

[functions.jarvio-assistant]
verify_jwt = false
