import React from 'react';
import { format } from 'date-fns';
import { MoreVertical, Trash2, FileText, Table, TrendingUp, Layout, Bot, Clock, ExternalLink } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { DocumentMetadata, DocumentType } from '@/types/docs';

interface DocumentCardProps {
  document: DocumentMetadata;
  onSelect: () => void;
  onDelete: () => void;
  onViewFlow?: (flowId: string) => void;
}

export function DocumentCard({ document, onSelect, onDelete, onViewFlow }: DocumentCardProps) {
  const getTypeIcon = (type: DocumentType) => {
    switch (type) {
      case 'text': return FileText;
      case 'table': return Table;
      case 'output': return TrendingUp;
      case 'template': return Layout;
      default: return FileText;
    }
  };

  const getTypeColor = (type: DocumentType) => {
    switch (type) {
      case 'text': return 'text-blue-600';
      case 'table': return 'text-green-600';
      case 'output': return 'text-purple-600';
      case 'template': return 'text-orange-600';
      default: return 'text-gray-600';
    }
  };

  const getStatusBadgeVariant = (status: string) => {
    switch (status) {
      case 'active': return 'success';
      case 'paused': return 'warning';
      case 'error': return 'destructive';
      default: return 'secondary';
    }
  };

  const TypeIcon = getTypeIcon(document.type);

  return (
    <Card className="group hover:shadow-md transition-shadow cursor-pointer">
      <CardContent className="p-4">
        <div className="flex items-start justify-between mb-3">
          <div className="flex items-center gap-2 flex-1 min-w-0">
            <TypeIcon className={`h-4 w-4 ${getTypeColor(document.type)}`} />
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2 mb-1">
                <h3 
                  className="font-medium text-foreground truncate cursor-pointer hover:text-primary"
                  onClick={onSelect}
                  title={document.title}
                >
                  {document.title}
                </h3>
                {document.isAutoGenerated && (
                  <Badge variant="blue" className="h-5 text-xs px-1.5 shrink-0">
                    <Bot className="h-3 w-3 mr-1" />
                    Auto
                  </Badge>
                )}
              </div>
              {document.sourceFlow && (
                <div className="flex items-center gap-1 text-xs text-muted-foreground">
                  <span>Generated by</span>
                  <Button
                    variant="link"
                    size="sm"
                    className="h-auto p-0 text-xs font-medium text-primary hover:underline"
                    onClick={(e) => {
                      e.stopPropagation();
                      onViewFlow?.(document.sourceFlow!.id);
                    }}
                  >
                    {document.sourceFlow.name}
                    <ExternalLink className="h-3 w-3 ml-1" />
                  </Button>
                </div>
              )}
            </div>
          </div>
          
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant="ghost"
                size="sm"
                className="h-8 w-8 p-0 opacity-0 group-hover:opacity-100 transition-opacity"
              >
                <MoreVertical className="h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              {document.sourceFlow && (
                <DropdownMenuItem 
                  onClick={(e) => {
                    e.stopPropagation();
                    onViewFlow?.(document.sourceFlow!.id);
                  }}
                >
                  <ExternalLink className="h-4 w-4 mr-2" />
                  View Flow
                </DropdownMenuItem>
              )}
              <DropdownMenuItem onClick={onDelete} className="text-destructive">
                <Trash2 className="h-4 w-4 mr-2" />
                Delete
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>

        <div className="space-y-2" onClick={onSelect}>
          {document.description && (
            <p className="text-sm text-muted-foreground line-clamp-2">
              {document.description}
            </p>
          )}
          
          {/* Flow Status and Frequency */}
          {document.sourceFlow && (
            <div className="flex items-center gap-2 mb-2">
              <Badge variant={getStatusBadgeVariant(document.sourceFlow.status)} className="h-5 text-xs">
                {document.sourceFlow.status}
              </Badge>
              <div className="flex items-center gap-1 text-xs text-muted-foreground">
                <Clock className="h-3 w-3" />
                <span>{document.sourceFlow.frequency}</span>
              </div>
            </div>
          )}
          
          <div className="flex items-center justify-between text-xs text-muted-foreground">
            <span>
              {document.wordCount} words
            </span>
            <span>
              {format(new Date(document.updatedAt), 'MMM d')}
            </span>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}