export type DocumentType = 'text' | 'table' | 'output' | 'template';
export type DocumentCategory = 'documents' | 'outputs' | 'templates';

export interface Document {
  id: string;
  title: string;
  content: string;
  type: DocumentType;
  category: DocumentCategory;
  createdAt: Date;
  updatedAt: Date;
  wordCount: number;
  characterCount: number;
  icon?: string;
  description?: string;
  // Flow-related fields
  sourceFlow?: {
    id: string;
    name: string;
    lastRun?: Date;
    status: 'active' | 'paused' | 'error';
    frequency?: string;
  };
  isAutoGenerated?: boolean;
}

export interface DocumentMetadata {
  id: string;
  title: string;
  type: DocumentType;
  category: DocumentCategory;
  createdAt: Date;
  updatedAt: Date;
  wordCount: number;
  characterCount: number;
  icon?: string;
  description?: string;
  // Flow-related fields
  sourceFlow?: {
    id: string;
    name: string;
    lastRun?: Date;
    status: 'active' | 'paused' | 'error';
    frequency?: string;
  };
  isAutoGenerated?: boolean;
}

export interface EditorState {
  currentDocument: Document | null;
  isLoading: boolean;
  isSaving: boolean;
  lastSaved?: Date;
}