-- Clear existing blocks
DELETE FROM flow_block_configs;

-- Insert new blocks with proper categorization

-- ACT BLOCKS (Actions/Output)
INSERT INTO flow_block_configs (block_name, block_type, config_data, is_functional) VALUES
('Send Email Notification', 'act', '{"description": "Sends an email from noreply@jarvio.io to a specified recipient. Ideal for notifying your team, sending alerts, or confirming task executions as part of a workflow. Requires Email Subject, Body, and Recipient.", "parameters": ["Email Body", "Email Subject", "Recipient"]}', true),
('Store Insight in Jarvio', 'act', '{"description": "This block logs a new Insight entry in your Jarvio account. It uses Jarvio''s Insights feature to store a record with the title, category, related listing, and description you provide. Essentially, it captures important information or observations directly into Jarvio for later review or tracking.", "parameters": ["Title", "Category", "Related Listings", "Description"]}', true),
('Create Task in Jarvio', 'act', '{"description": "This block creates a new task in your Jarvio workspace. It uses Jarvio''s task management system to add a task with the specified name, description, category, status, and due date. This allows your team to track follow-up actions or to-dos generated automatically within your workflow.", "parameters": ["Task Name", "Task Description", "Category", "Status", "Priority"]}', true),
('Trigger External Webhook', 'act', '{"description": "Use this block when you need to push data from your Jarvio automation to an outside system or service. For example, trigger a webhook to notify a third-party app (like Slack, a database, or another API) after an event occurs or data is gathered in your workflow.", "parameters": ["Webhook URL", "Request Body"]}', true);

-- COLLECT BLOCKS (Data gathering)
INSERT INTO flow_block_configs (block_name, block_type, config_data, is_functional) VALUES
('Get ASIN Data from Amazon', 'collect', '{"description": "This block retrieves detailed product data for one or more ASINs directly from your Amazon seller account using Amazon''s Selling Partner API. It can pull various metrics and information (like sales figures, inventory levels, etc.) for the specified ASINs over a given date range. Use this block when you want to gather the latest performance metrics or details for one or more of your Amazon products.", "parameters": ["ASINs", "Metrics", "Date Range"]}', true),
('Scrape External Webpage', 'collect', '{"description": "This block scrapes the content of any webpage given its URL and returns that page''s data. It uses Jarvio''s web scraping capability to fetch the HTML content directly from the site (outside of Amazon''s systems). This is useful for pulling information from external websites or competitor pages into your workflow for analysis or record-keeping.", "parameters": ["URL"]}', true),
('Get Account-Level Data from Amazon', 'collect', '{"description": "This block pulls high-level account metrics directly from your Amazon seller account via Amazon''s Selling Partner API. It retrieves overall performance data such as total sales, order counts, or other account-wide statistics over a specified date range. Use this block to get a snapshot of your overall Amazon business performance.", "parameters": ["Metrics", "Date Range"]}', true),
('Analyse an eCommerce Website', 'collect', '{"description": "This block scrapes a given eCommerce website (for example, a Shopify store) and summarizes key information about that brand or site. It uses a web scraper to gather publicly available data from the site''s pages, then produces an overview of the store – such as its product range, apparent branding, and notable features.", "parameters": ["URL"]}', true),
('Amazon Review Sentiment Analyzer', 'collect', '{"description": "This block analyzes customer feedback by pulling reviews for a specified ASIN and then determining the overall sentiment of those reviews. It automatically gathers recent reviews from Amazon and uses a machine learning model to identify whether the sentiment is positive, negative, or neutral, providing you with a summary of how customers feel about the product. This offers a quick way to gauge customer satisfaction and spot issues without manually reading all reviews.", "parameters": ["ASIN"]}', true),
('ASPI Amazon Product Image Analysis', 'collect', '{"description": "This block pulls images from in ASIN in your own account, then runs these through ASPI image best practices to give a comprehensive summary of the image presence quality.", "parameters": ["ASIN"]}', true),
('Custom Amazon Product Image Analyzer', 'collect', '{"description": "This block provides an AI-driven analysis of a product''s images for a given ASIN. After retrieving all the listing images from Amazon, it lets you pose a question or prompt to an AI vision model about those images. The AI will analyze the visual content to answer your query or provide insights. For example, you could ask if the images meet Amazon''s requirements or have the AI describe the product''s appearance across the photos.", "parameters": ["Prompt", "ASIN"]}', true),
('JungleScout ASIN Keyword Data', 'collect', '{"description": "Use this block when you want to uncover which search terms are driving traffic to a product. For example, if you have a competitor''s ASIN, run this to get a list of keywords that product ranks for — which can inform your own SEO or advertising strategy. It''s also useful for checking your own product''s reach: see if you''re indexing for all relevant keywords.", "parameters": ["ASIN(s)"]}', true),
('JungleScout Keyword Metrics', 'collect', '{"description": "This block fetches key metrics for a given Amazon search term using JungleScout''s keyword database. It returns data such as the term''s estimated monthly search volume, level of competition, and other related metrics. Powered by JungleScout''s API, it provides a quick overview of how popular and competitive a specific keyword is in the Amazon marketplace.", "parameters": ["Keyword"]}', true),
('Scrape Amazon Product Details', 'collect', '{"description": "This block scrapes the Amazon product listing page for a specified ASIN to extract detailed information about that product. It gathers data such as the title, description, bullet points, images, and other listing content directly from Amazon''s website. This is especially useful for retrieving product details for any ASIN (including competitor products not in your seller account), since it fetches the live listing information through web scraping rather than your own account.", "parameters": ["ASIN"]}', true),
('Scrape Amazon Product Offers', 'collect', '{"description": "This block scrapes the Amazon offer listings page for a given ASIN to collect information on all current sellers offering that product. It retrieves details like each seller''s price, shipping options, condition (new/used), and other offer specifics by scanning the Amazon site. In short, it provides a snapshot of the competitive selling landscape for that product – who the sellers are and at what prices they''re offering the item.", "parameters": ["ASIN"]}', true),
('Get Category Tree from Amazon', 'collect', '{"description": "Use this block whenever you need to explore Amazon''s category hierarchy, especially if you''re unsure where a product should be listed or want to find related subcategories. For example, if you have a category ID or name and want to see all subdivisions beneath it, this block will map them out for you.", "parameters": ["Category ID or Category Name"]}', true),
('Get Category Best Sellers from Amazon', 'collect', '{"description": "This block retrieves the top-ranked products in a given Amazon category – for example, the Best Sellers list for that category. It queries Amazon''s site to pull the highest performing items (and can be configured to get related lists like New Releases or Movers & Shakers) for the category you specify. The result is a list of the most popular products in that category, which is valuable for market research and for understanding which items lead the pack in that niche.", "parameters": ["Category ID", "Type (Best Sellers, New Releases, Movers & Shakers)"]}', true),
('Get Top Products from Amazon Category', 'collect', '{"description": "This block gathers a broad list of top products from a specified Amazon category. It scans the category on Amazon to collect a number of the most popular or high-ranking items (for instance, the top 50-60 products). This gives you an overview of the key products in that category beyond just the very top few, useful for a more extensive competitive analysis or product research within that category.", "parameters": ["Category ID"]}', true),
('Scrape Amazon Product Reviews', 'collect', '{"description": "This block scrapes customer reviews for a specified Amazon product (ASIN) directly from Amazon''s website. It collects the text of reviews, star ratings, and other review details by navigating through the product''s review pages. By using this block, you can obtain raw review data for further analysis or insight – especially handy for products where you want to read or process customer feedback for competitors.", "parameters": ["ASIN"]}', true),
('Scrape Amazon Seller Profile', 'collect', '{"description": "This block scrapes the public profile page of an Amazon seller to gather information about that seller. It retrieves details such as the seller''s name, business information, ratings, and feedback score from Amazon''s site. This helps you quickly check a seller''s credibility and background – for example, to see their ratings and how long they''ve been active – when evaluating potential competitors or partners on Amazon.", "parameters": ["Seller ID"]}', true),
('Scrape Amazon Seller Products', 'collect', '{"description": "This block scrapes the product listings from a specific Amazon seller''s storefront. It visits the seller''s page on Amazon and collects information on all products that seller offers (like ASINs, product titles, and possibly prices). Using this block, you can get a full view of a competitor''s product catalog on Amazon, which is useful for competitor analysis or tracking what products a particular seller is carrying.", "parameters": ["seller_id (str)"]}', true),
('Scrape Amazon Search Results', 'collect', '{"description": "This block scrapes the Amazon search results for a given keyword query. It performs a search on Amazon using your specified term and then gathers the list of product results (ASINs and titles) that appear on the search results page. This allows you to see which products (and by extension, which brands or sellers) are ranking for that keyword, providing insight into the competition and visibility for that search term.", "parameters": ["Keyword"]}', true),
('Reverse ASIN Keyword Research', 'collect', '{"description": "This block finds relevant search keywords for a given product via a reverse ASIN lookup. You provide an ASIN, and the block uses an external Amazon keyword research engine to generate a list of the most important search terms associated with that product''s listing. In short, it shows you which keywords are likely driving traffic to the product, helping you identify target terms for SEO or advertising.", "parameters": ["ASIN"]}', true),
('Amazon Keyword Metrics', 'collect', '{"description": "This block retrieves key metrics for a specific Amazon search term using an external keyword database. It provides data such as the estimated search volume for the keyword, typical cost-per-click (CPC) in ads, and other popularity or competition indicators. By using this block, you can gauge how valuable and competitive a given keyword is, which aids in deciding whether to target that term in your product listing or advertising campaigns.", "parameters": ["Keyword"]}', true),
('Amazon Product Trends', 'collect', '{"description": "This block pulls historical trend data for a given Amazon product (ASIN), focusing on metrics like price, sales rank, and estimated units sold over time. It uses an external product tracking service to fetch recent trends, so you can see how the product''s price and popularity have changed (for example, whether the sales rank improved after a price drop). This helps in analyzing performance patterns, seasonality, and the impact of changes on the product''s success.", "parameters": ["ASIN", "Metrics (Price, BSR, Rating, Review Count, Seller Count)"]}', true),
('JungleScout Sales Estimator', 'collect', '{"description": "This block provides an estimated sales volume for a specific ASIN using JungleScout''s data models. It leverages JungleScout''s analysis of Amazon sales ranks and other factors to approximate how many units of that product are selling per month (or over a given period). This is especially useful for evaluating competitor products or potential products you don''t sell yourself, as it gives insight into market demand without needing actual sales data from a seller account.", "parameters": ["ASIN", "Start Date", "End Date"]}', true),
('JungleScout Share of Voice', 'collect', '{"description": "This block measures brand share-of-voice on Amazon for a given search term using JungleScout''s API. It analyzes the top search results for your specified keyword and determines which brands (or sellers) occupy the most spots, effectively showing the percentage of visibility each brand has on that search''s first page. This insight helps you understand how dominant certain brands are for that keyword, which is valuable for competitive analysis and monitoring your own brand''s visibility.", "parameters": ["Keyword"]}', true),
('JungleScout Product Database Query', 'collect', '{"description": "Use this block for advanced product scouting and research. For instance, if you have a specific set of criteria for a product idea (say, \"Pet Supplies category, $20-$30 price, under 100 reviews, selling at least 300 units/month\"), you can plug those filters in and instantly get a list of products that match. It''s a huge time-saver for finding products that meet your exact investment criteria.", "parameters": ["28 Parameters that can be configured"]}', true),
('JungleScout Reverse Product Search', 'collect', '{"description": "Use this block when you want to discover products related to ones you already know about, especially under certain constraints. For example, if you have a list of successful ASINs from competitors, you could input them and ask for others with similar profiles (maybe similar category or features) that also meet a high sales threshold. It''s a way to broaden your research from known winners to find other potential opportunities.", "parameters": ["asins (List[str])", "same extensive filtering options as Product Database Query"]}', true),
('JungleScout Historical Search Volume', 'collect', '{"description": "This block retrieves the historical search volume trend for a given keyword using JungleScout''s data. It provides a month-by-month (or time series) overview of how often that term has been searched on Amazon over time. By examining these trends, you can identify seasonal patterns or growth and decline in a keyword''s popularity. It''s useful for understanding the long-term value of a search term – for example, whether a keyword is steadily rising in popularity or only peaks during certain months.", "parameters": ["Keyword", "Start Date", "End Date"]}', true);

-- THINK BLOCKS (Analysis)
INSERT INTO flow_block_configs (block_name, block_type, config_data, is_functional) VALUES
('Support Case Wizard', 'think', '{"description": "Use this block whenever you need to create or escalate an issue with Amazon Seller Support and want guidance in formulating the case. For example, if a product listing has been incorrectly suspended or you encounter an inventory discrepancy, the wizard can compile the key details into a support case format that you can then submit to Amazon.", "parameters": ["Prompt"]}', true);