// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aojrdgobdavxjpnymskc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvanJkZ29iZGF2eGpwbnltc2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzOTI1MTAsImV4cCI6MjA1NTk2ODUxMH0.wMoKqcb8N_r5xqLmLwhwHgjzvp-MautqCzsOxNzmucs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);