import { DocumentMetadata } from '@/types/docs';

export const sampleDocuments: DocumentMetadata[] = [
  // My Documents folder
  {
    id: 'doc-1',
    title: 'Amazon Listing Optimization Guide',
    type: 'text',
    category: 'documents',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20'),
    wordCount: 1247,
    characterCount: 7580,
    description: 'Complete guide for optimizing product listings on Amazon marketplace'
  },
  {
    id: 'doc-2',
    title: 'Q4 Inventory Restock Plan',
    type: 'table',
    category: 'documents',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-22'),
    wordCount: 456,
    characterCount: 2890,
    description: 'Quarterly inventory planning and restock analysis'
  },
  {
    id: 'doc-3',
    title: 'Competitor Analysis - Electronics',
    type: 'text',
    category: 'documents',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-19'),
    wordCount: 892,
    characterCount: 5320,
    description: 'Deep dive into competitor pricing and positioning strategies'
  },
  {
    id: 'doc-4',
    title: 'Product Launch Timeline',
    type: 'table',
    category: 'documents',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-16'),
    wordCount: 634,
    characterCount: 3890,
    description: 'Step-by-step timeline for new product launches'
  },
  {
    id: 'doc-5',
    title: 'Customer Feedback Analysis',
    type: 'text',
    category: 'documents',
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-21'),
    wordCount: 728,
    characterCount: 4200,
    description: 'Analysis of customer reviews and feedback patterns'
  },

  // Outputs folder
  {
    id: 'flow-output-1',
    title: 'Inventory Restock Flow Output',
    type: 'output',
    category: 'outputs',
    createdAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-01-28'),
    wordCount: 456,
    characterCount: 2890,
    description: 'Automated inventory restock analysis and recommendations',
    sourceFlow: {
      id: 'flow-1',
      name: 'Inventory Restock Monitor',
      lastRun: new Date('2024-01-28'),
      status: 'active',
      frequency: 'Daily at 6 AM'
    },
    isAutoGenerated: true
  },
  {
    id: 'flow-output-2',
    title: 'Listing Optimisation Flow Output',
    type: 'output',
    category: 'outputs',
    createdAt: new Date('2024-01-24'),
    updatedAt: new Date('2024-01-24'),
    wordCount: 634,
    characterCount: 3890,
    description: 'Product listing optimization recommendations and changes',
    sourceFlow: {
      id: 'flow-2',
      name: 'Listing Optimizer',
      lastRun: new Date('2024-01-24'),
      status: 'active',
      frequency: 'Weekly on Mondays'
    },
    isAutoGenerated: true
  },
  {
    id: 'flow-output-3',
    title: 'Perfect Amazon Listing Creation Output',
    type: 'output',
    category: 'outputs',
    createdAt: new Date('2024-01-27'),
    updatedAt: new Date('2024-01-27'),
    wordCount: 892,
    characterCount: 5320,
    description: 'Complete optimized Amazon product listing',
    sourceFlow: {
      id: 'flow-3',
      name: 'Perfect Listing Creator',
      lastRun: new Date('2024-01-27'),
      status: 'active',
      frequency: 'On demand'
    },
    isAutoGenerated: true
  },
  {
    id: 'output-1',
    title: 'Product Performance Analysis Report',
    type: 'output',
    category: 'outputs',
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
    wordCount: 892,
    characterCount: 5320,
    description: 'AI-generated analysis of product performance metrics',
    sourceFlow: {
      id: 'flow-4',
      name: 'Performance Analyzer',
      lastRun: new Date('2024-01-18'),
      status: 'active',
      frequency: 'Daily at 9 AM'
    },
    isAutoGenerated: true
  },
  {
    id: 'output-2',
    title: 'Competitor Pricing Report',
    type: 'output',
    category: 'outputs',
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
    wordCount: 634,
    characterCount: 3890,
    description: 'Automated competitor pricing analysis and recommendations',
    sourceFlow: {
      id: 'flow-5',
      name: 'Competitor Price Monitor',
      lastRun: new Date('2024-01-16'),
      status: 'active',
      frequency: 'Every 4 hours'
    },
    isAutoGenerated: true
  },
  {
    id: 'output-3',
    title: 'Inventory Optimization Suggestions',
    type: 'output',
    category: 'outputs',
    createdAt: new Date('2024-01-17'),
    updatedAt: new Date('2024-01-17'),
    wordCount: 567,
    characterCount: 3450,
    description: 'AI recommendations for inventory management optimization',
    sourceFlow: {
      id: 'flow-6',
      name: 'Inventory Optimizer',
      lastRun: new Date('2024-01-17'),
      status: 'paused',
      frequency: 'Twice weekly'
    },
    isAutoGenerated: true
  },
  {
    id: 'output-4',
    title: 'Keyword Research Analysis',
    type: 'output',
    category: 'outputs',
    createdAt: new Date('2024-01-19'),
    updatedAt: new Date('2024-01-19'),
    wordCount: 445,
    characterCount: 2890,
    description: 'Automated keyword research and SEO recommendations',
    sourceFlow: {
      id: 'flow-7',
      name: 'Keyword Research Bot',
      lastRun: new Date('2024-01-19'),
      status: 'active',
      frequency: 'Weekly on Fridays'
    },
    isAutoGenerated: true
  },
  {
    id: 'output-5',
    title: 'Sales Trend Forecast',
    type: 'output',
    category: 'outputs',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
    wordCount: 723,
    characterCount: 4100,
    description: 'AI-powered sales forecasting based on historical data',
    sourceFlow: {
      id: 'flow-8',
      name: 'Sales Forecaster',
      lastRun: new Date('2024-01-20'),
      status: 'active',
      frequency: 'Daily at 11 PM'
    },
    isAutoGenerated: true
  },

  // Templates folder
  {
    id: 'template-1',
    title: 'Product Launch Checklist',
    type: 'template',
    category: 'templates',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
    wordCount: 523,
    characterCount: 3210,
    description: 'Template for new product launch planning'
  },
  {
    id: 'template-2',
    title: 'Monthly Review Template',
    type: 'template',
    category: 'templates',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
    wordCount: 287,
    characterCount: 1890,
    description: 'Template for monthly business performance reviews'
  },
  {
    id: 'template-3',
    title: 'Competitor Analysis Framework',
    type: 'template',
    category: 'templates',
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-06'),
    wordCount: 398,
    characterCount: 2340,
    description: 'Structured template for competitor analysis'
  }
];

// Sample document contents
export const sampleDocumentContents: Record<string, string> = {
  'flow-output-1': `# Inventory Restock Flow Output

**Flow Execution Date:** July 28, 2025
**Status:** Completed Successfully

## Restock Recommendations

### Critical Items (Immediate Action Required)
- **Wireless Headphones Pro**: Current Stock: 12 units | Recommended Restock: 200 units
- **Bluetooth Speakers**: Current Stock: 8 units | Recommended Restock: 150 units

### Medium Priority Items
- **Phone Cases**: Current Stock: 45 units | Recommended Restock: 100 units
- **Charging Cables**: Current Stock: 67 units | Recommended Restock: 80 units

## Analysis Summary
- Total investment needed: $45,000
- Expected ROI: 35%
- Lead time average: 14 days
- Supplier recommendations included

## Next Steps
1. Contact TechSupply Co for headphones order
2. Negotiate bulk pricing for speakers
3. Schedule delivery for next week`,

  'flow-output-2': `# Listing Optimisation Flow Output

**Flow Execution Date:** July 24, 2025
**Product:** Wireless Bluetooth Headphones Pro
**Status:** Optimization Complete

## Original vs Optimized Comparison

### Title Optimization
**Before:** Bluetooth Headphones Wireless
**After:** Wireless Bluetooth Headphones Pro - Noise Cancelling, 30Hr Battery, Fast Charging

### Key Improvements Made
1. **Enhanced Title**: Added key features and benefits
2. **Optimized Bullet Points**: Focused on customer pain points
3. **Improved Images**: Added lifestyle and feature highlight images
4. **Updated Description**: More compelling copy with technical specs

## Performance Predictions
- Expected CTR improvement: +25%
- Estimated conversion rate increase: +18%
- Projected sales increase: +35%

## Implementation Status
✅ Title updated
✅ Images uploaded
✅ Description revised
⏳ A+ Content pending approval`,

  'flow-output-3': `# Perfect Amazon Listing Creation Output

**Flow Execution Date:** July 27, 2025
**Product:** Premium Noise-Cancelling Bluetooth Headphones
**Status:** Listing Created Successfully

## Complete Listing Details

### Optimized Title
Premium Noise-Cancelling Bluetooth Headphones - 40Hr Battery, Quick Charge, Hi-Fi Sound, Comfortable Over-Ear Design

### Key Features (Bullet Points)
• **Superior Noise Cancellation** - Advanced ANC technology blocks 95% of ambient noise
• **Extended Battery Life** - 40 hours playtime with ANC, 60 hours without
• **Premium Sound Quality** - Hi-Fi drivers deliver crisp highs and deep bass
• **Comfort Focused** - Memory foam ear cups for all-day wearing comfort
• **Quick Charging** - 15 minutes charge provides 3 hours of playback

### Product Description
Experience audio like never before with our Premium Noise-Cancelling Bluetooth Headphones. Engineered for audiophiles and professionals who demand the best in sound quality and comfort.

### Pricing Strategy
- Launch Price: $199.99
- Competitor Analysis: 15% below premium competitors
- Promotional Strategy: 20% off for first 100 customers

## Launch Checklist
✅ Product photography completed
✅ A+ Content created
✅ PPC campaigns set up
✅ Inventory secured (500 units)
⏳ Launch scheduled for next Monday`,

  'doc-1': `# Amazon Listing Optimization Guide

## Overview
This comprehensive guide covers best practices for optimizing Amazon product listings to maximize visibility and conversions.

## Key Optimization Areas

### 1. Title Optimization
- Include primary keywords naturally
- Mention key features and benefits
- Follow Amazon's title guidelines
- Keep under 200 characters

### 2. Product Images
- High-quality, professional images
- Multiple angles and lifestyle shots
- Infographic highlighting key features
- A+ Content integration

### 3. Bullet Points
- Focus on benefits, not just features
- Use relevant keywords naturally
- Address common customer concerns
- Highlight unique selling propositions

### 4. Product Description
- Detailed feature explanations
- Use cases and applications
- Technical specifications
- Brand story integration

## Performance Tracking
Monitor key metrics:
- Click-through rate (CTR)
- Conversion rate
- Search ranking positions
- Customer review sentiment`,

  'doc-2': `# Q4 Inventory Restock Plan

| Product | Current Stock | Projected Demand | Restock Quantity | Supplier | Lead Time | Priority |
|---------|---------------|------------------|------------------|----------|-----------|----------|
| Wireless Headphones | 45 | 200 | 180 | TechSupply Co | 14 days | High |
| Phone Cases | 120 | 300 | 200 | CaseWorld | 7 days | High |
| Screen Protectors | 80 | 250 | 190 | ProtectPro | 10 days | Medium |
| Charging Cables | 200 | 400 | 250 | ElectroSupply | 12 days | Medium |
| Bluetooth Speakers | 30 | 150 | 130 | AudioTech | 21 days | High |

## Key Insights
- Total investment needed: $45,000
- Expected ROI: 35%
- Critical items: Headphones, Speakers (low stock)
- Supplier diversification needed for cables`,

  'output-1': `# Product Performance Analysis Report

Generated on: January 18, 2024

## Executive Summary
This automated analysis reveals key performance trends across your product portfolio for the past quarter.

## Top Performers
1. **Wireless Headphones Pro** - 156% growth
2. **Premium Phone Case Series** - 89% growth  
3. **Fast Charging Bundle** - 67% growth

## Areas for Improvement
- Bluetooth speakers showing declining sales (-12%)
- Screen protector conversion rate below average (2.1%)
- Customer complaints increasing for charging cables

## Recommendations
1. Increase marketing spend on top performers
2. Review pricing strategy for bluetooth speakers
3. Improve product images for screen protectors
4. Address quality issues with charging cables`,

  'output-2': `# Competitor Pricing Report

Analysis Date: January 16, 2024
Market: Consumer Electronics

## Pricing Comparison Matrix

**Wireless Headphones Category:**
- Our Price: $89.99
- Competitor A: $94.99 (+5.6%)
- Competitor B: $84.99 (-5.6%)
- Market Average: $88.45

**Phone Cases Category:**
- Our Price: $24.99
- Competitor A: $27.99 (+12%)
- Competitor B: $22.99 (-8%)
- Market Average: $25.32

## Strategic Recommendations
1. Consider price reduction for headphones to match market leader
2. Maintain current phone case pricing - well positioned
3. Monitor Competitor B's aggressive pricing strategy`,

  'template-1': `# Product Launch Checklist Template

## Pre-Launch Phase (8 weeks before)
- [ ] Market research and competitor analysis
- [ ] Product photography and content creation
- [ ] Amazon listing optimization
- [ ] Inventory planning and procurement
- [ ] PPC campaign setup

## Launch Phase (Launch week)
- [ ] Product listing goes live
- [ ] Launch PPC campaigns
- [ ] Social media announcements
- [ ] Email marketing to existing customers
- [ ] Monitor for any issues

## Post-Launch Phase (4 weeks after)
- [ ] Performance review and optimization
- [ ] Customer feedback analysis
- [ ] Inventory level monitoring
- [ ] PPC campaign optimization
- [ ] Plan next phase strategies`,

  'template-2': `# Monthly Review Template

## Sales Performance
- Total Revenue: $______
- Units Sold: ______
- Average Order Value: $______
- Conversion Rate: _____%

## Key Metrics
- Traffic Growth: _____%
- Customer Acquisition Cost: $______
- Return Rate: _____%
- Customer Satisfaction Score: ______

## Top Performing Products
1. ________________
2. ________________
3. ________________

## Areas for Improvement
- ________________
- ________________
- ________________

## Action Items for Next Month
- [ ] ________________
- [ ] ________________
- [ ] ________________`
};